name: build & package (win32 release)

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        os: [windows-2022]   # only Windows host
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set TAG_NAME env var
        shell: bash
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Set PKG_NAME env var
        shell: bash
        run: echo "PKG_NAME=tcl" >> $GITHUB_ENV

      - name: Setup MSYS2 in Windows (mingw32)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          pacboy: |
            make: diffutils: patch: gcc

      - name: Build in Windows (mingw32, release)
        shell: msys2 {0}
        env:
          BUILD_MODE: release
        run: |
          sh build.sh

      - name: Upload log for debugging configure step
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: config-log_win32_release
          path: config.log

      - name: Quick test
        shell: msys2 {0}
        run: |
          TCLSH=$(find ./$PKG_NAME/bin/ -type f -name 'tclsh8.4*')
          echo "puts hello_world; exit;" | $TCLSH

      - name: Upload package for publishing job
        uses: actions/upload-artifact@v4
        with:
          name: package_win32_release
          path: |
            *.tar.xz

  Publish:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: package_*
          merge-multiple: true
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.tar.xz
